// Root layout - minimal, locale-specific layout is in [locale]/layout.jsx
export const metadata = {
  title: {
    default: 'AqaarGate - Best Real Estate Sites in Syria | #1 Platform | Buy, Rent & Sell Properties',
    template: '%s | AqaarGate - Best Real Estate Sites in Syria'
  },
  description: 'AqaarGate is one of the best real estate sites in Syria. The #1 real estate platform in Syria & Lattakia. Find luxury homes, apartments, holiday homes (بيوت عطلات سوريا), villas for sale and rent. Trusted by expats from Germany, Netherlands, EU, UAE, Saudi Arabia, Qatar, Kuwait. Browse 1000+ verified properties. Start your search today!',
  keywords: [
    // Arabic - موقع عقاري، عقارات في سورية
    'موقع عقاري',
    'موقع عقارات',
    'منصة عقارات في سورية',
    'منصة عقارات في سوريا',
    'عقارات سورية',
    // Brand + exact search phrase for "best real estate sites in syria"
    'best real estate sites in syria',
    'best real estate sites in Syria',
    'aqaargate',
    'aqaargate.com',
    'aqaargate real estate',
    'aqaargate syria',
    'aqaargate lattakia',
    'aqaargate properties',
    'aqaargate عقارات',
    // Syria and Lattakia keywords (exact phrases)
    'syria real estate',
    'buy property in Syria',
    'apartments for sale Damascus',
    'apartments for sale in Damascus',
    'Syrian property platform',
    'homes for sale in Syria',
    'Syrian property market',
    'land for sale Syria',
    'property investment Syria',
    'expat property Syria',
    'houses for rent Syria',
    'real estate opportunities in Syria',
    'affordable properties in Syria',
    'real estate syria',
    'properties syria',
    'lattakia properties',
    'lattakia real estate',
    'properties for sale syria',
    'properties for rent syria',
    'syria apartments',
    'syria houses',
    'lattakia apartments',
    'lattakia houses',
    'syria holiday homes',
    'syria vacation rentals',
    'lattakia holiday homes',
    'lattakia vacation rentals',
    'syria property listings',
    'lattakia property listings',
    'real estate lattakia',
    'property management syria',
    'syria real estate agent',
    'lattakia real estate agent',
    'syria home buying',
    'syria home selling',
    'lattakia home buying',
    'lattakia home selling',
    'syria commercial properties',
    'lattakia commercial properties',
    'syria luxury homes',
    'lattakia luxury homes',
    'syria property search',
    'lattakia property search',
    'syria real estate listings',
    'lattakia real estate listings',
    'syria property investment',
    'lattakia property investment',
    'syria beach properties',
    'lattakia beach properties',
    'syria coastal properties',
    'lattakia coastal properties',
    'syria villas',
    'lattakia villas',
    'syria condos',
    'lattakia condos',
    'apartments for rent Damascus',
    'apartments for rent Syria',
    'chalet for sale Syria',
    'chalet for rent Syria',
    'chalet Tartous',
    'farm for sale Syria',
    'commercial property Syria',
    'townhouse Syria',
    'studio apartment Damascus',
    'studio apartment Syria',
    'Rif Dimashq',
    'Damascus countryside',
    'buy property Syria online',
    'syria property portal',
    'syria property listing',
    'syria land for sale',
    'lattakia land for sale',
    'syria rental properties',
    'lattakia rental properties',
    // International keywords - EU countries searching for Syria properties
    'syria real estate from germany',
    'syria properties germany',
    'syria real estate deutschland',
    'syria properties netherlands',
    'syria real estate netherlands',
    'syria properties from netherlands',
    'syria real estate from europe',
    'syria properties eu',
    'syria real estate europe',
    'buy property syria from germany',
    'buy property syria from netherlands',
    'buy property syria from europe',
    'syria real estate for expats',
    'syria properties expats',
    'syria real estate expatriates',
    'syria property investment germany',
    'syria property investment netherlands',
    'syria property investment europe',
    'syria holiday homes expats',
    'syria vacation rentals expats',
    'syria real estate for germans',
    'syria real estate for dutch',
    // International keywords - Arab Gulf countries searching for Syria properties
    'syria real estate from uae',
    'syria properties uae',
    'syria real estate dubai',
    'syria properties dubai',
    'syria real estate from saudi arabia',
    'syria properties saudi arabia',
    'syria real estate riyadh',
    'syria properties riyadh',
    'syria real estate from qatar',
    'syria properties qatar',
    'syria real estate doha',
    'syria properties doha',
    'syria real estate from kuwait',
    'syria properties kuwait',
    'syria real estate kuwait city',
    'syria properties kuwait city',
    'syria real estate from bahrain',
    'syria properties bahrain',
    'syria real estate manama',
    'syria properties manama',
    'syria real estate from oman',
    'syria properties oman',
    'syria real estate muscat',
    'syria properties muscat',
    'syria real estate gulf',
    'syria properties gulf countries',
    'buy property syria from uae',
    'buy property syria from saudi arabia',
    'buy property syria from qatar',
    'buy property syria from kuwait',
    'buy property syria from bahrain',
    'buy property syria from oman',
    'invest syria from gulf',
    'syria property investment uae',
    'syria property investment saudi arabia',
    'syria property investment qatar',
    'syria property investment kuwait',
    'syria property investment bahrain',
    'syria property investment oman',
    'syria real estate for emirates',
    'syria real estate for saudis',
    'syria real estate for qataris',
    'syria real estate for kuwaitis',
    // Syrian dialect - لهجة سورية (كراء = إيجار)
    'شقة للكراء',
    'بيت للكراء',
    'عقار للكراء',
    'شقة مفروشة للكراء',
    'شقة مفروشة للايجار',
    'شقة غير مفروشة',
    'بيت للبيع',
    'عمارة للبيع',
    'عمارة للايجار',
    'استراحة للبيع',
    'استراحة للايجار',
    'شاليه للبيع',
    'شاليه للايجار',
    'دكان للايجار',
    'محلات للايجار',
    'شراء عقار من برا',
    'عقار من برا',
    'عقارات من برا',
    'ريف دمشق',
    'عقارات ريف دمشق',
    'عقارات ريف دمشق للبيع',
    'مكتب عقاري دمشق',
    'وسيط عقاري',
    'مكتب عقاري اللاذقية',
    // Local search variations - Arabic keywords (exact phrases for top search, ikar.sy-style)
    'افضل المواقع العقارية في سوريا',
    'أفضل المواقع العقارية في سوريا',
    'افضل موقع عقاري في سوريا',
    'أفضل موقع عقاري في سوريا',
    'سوق العقارات الالكتروني في سورية',
    'سوق العقارات الإلكتروني في سورية',
    'منصة عقارات في سورية',
    'بيع وشراء بيوت في سورية',
    'تأجير بيوت في سورية',
    'عقارات في سوريا',
    'مستقبل العقارات في دمشق وسوريا',
    'شقق للبيع في سوريا',
    'عقارات في حلب',
    'عقارات في دمشق',
    'شقة للبيع في دمشق',
    'شقة للاجار في دمشق',
    'عقارات للاجار في دمشق',
    'عقارات في اللاذقية',
    'شقة للاجار في اللاذقية',
    'شاليه في طرطوس',
    'عقارات في حمص',
    'عقارات للبيع في حمص',
    'عقارات للبيع في طرطوس',
    'عقارات للبيع في ريف دمشق',
    'عقارات اللاذقية للبيع',
    'عقارات حلب للبيع',
    'شقق للايجار في اللاذقية',
    'شقق للايجار في حلب',
    'شقق للايجار في حمص',
    'فلل للبيع في سوريا',
    'فلل للبيع في دمشق',
    'فلل للبيع في اللاذقية',
    'أراضي للبيع في دمشق',
    'أراضي للبيع في اللاذقية',
    'أراضي للبيع في ريف دمشق',
    'شقة استوديو دمشق',
    'شقة غرفتين دمشق',
    'شقة ثلاث غرف',
    'مكتب للاجار',
    'عيادة للاجار',
    'دكان للاجار',
    'محل للاجار',
    'عقارات سوريا',
    'شقق للبيع في دمشق',
    'منصة عقارية سوريا',
    'شراء عقار في سوريا',
    'عقارات موثوقة',
    'عقارات للمغتربين',
    'عقارات اللاذقية',
    'استثمار عقاري في سوريا',
    // Arabic equivalents of English key phrases
    'منازل للبيع في سوريا',
    'شقق للبيع في دمشق',
    'سوق العقارات السورية',
    'أراضي للبيع في سوريا',
    'عقارات للمغتربين',
    'منازل للإيجار في سوريا',
    'فرص عقارية في سوريا',
    'عقارات بأسعار معقولة في سوريا',
    'عقارات سوريا من الإمارات',
    'عقارات سوريا من السعودية',
    'عقارات سوريا من قطر',
    'عقارات سوريا من الكويت',
    // Holiday homes in Arabic
    'بيوت عطلات',
    'بيوت عطلات سوريا',
    'بيوت عطلات اللاذقية',
    'بيوت عطلات للبيع',
    'بيوت عطلات للإيجار',
    'بيع بيوت عطلات',
    'تأجير بيوت عطلات',
    'بيوت عطلات للبيع في سوريا',
    'بيوت عطلات للإيجار في سوريا',
    'بيع وتأجير بيوت',
    'بيع وتأجير بيوت عطلات',
    'بيع وتأجير بيوت في سوريا',
    'بيع وتأجير بيوت عطلات في سوريا',
    'بيوت عطلات على الشاطئ',
    'بيوت عطلات ساحلية',
    // Vacation rentals in Arabic
    'إيجار منازل عطلات',
    'منازل عطلات للايجار',
    'استئجار بيت عطلة',
    'بيوت عطلات للعائلات',
    // Holiday homes for expats in Arabic
    'بيوت عطلات للعرب',
    'بيوت عطلات للخليجيين',
    'بيوت عطلات في سوريا للعرب',
    'بيوت عطلات في سوريا للخليجيين'
  ],
  authors: [{ name: 'AqaarGate Real Estate Team' }],
  creator: 'AqaarGate Real Estate',
  publisher: 'AqaarGate Real Estate',
  formatDetection: {
    email: false,
    address: false,
    telephone: false,
  },
  metadataBase: new URL(process.env.NEXT_PUBLIC_SITE_URL || 'https://www.aqaargate.com'),
  openGraph: {
    type: 'website',
    locale: 'en_US',
    url: process.env.NEXT_PUBLIC_SITE_URL || 'https://www.aqaargate.com',
    siteName: 'AqaarGate',
    title: 'AqaarGate - Best Real Estate Sites in Syria | #1 Platform | Buy, Rent & Sell',
    description: 'AqaarGate is one of the best real estate sites in Syria. The #1 platform in Syria & Lattakia. 1000+ verified properties for sale and rent. Luxury homes, apartments, holiday homes (بيوت عطلات سوريا), villas. Trusted worldwide.',
    images: [
      { url: '/images/logo/og.png', width: 180, height: 180, alt: 'AqaarGate Real Estate', type: 'image/png' },
    ],
  },
  twitter: {
    card: 'summary_large_image',
    title: 'AqaarGate - Best Real Estate Sites in Syria | #1 Platform',
    description: 'One of the best real estate sites in Syria. AqaarGate - #1 platform in Syria & Lattakia. 1000+ properties for sale and rent. Holiday homes, villas, apartments. Trusted worldwide.',
    images: ['/images/logo/og.png'],
    creator: '@AqaarGate',
    site: '@AqaarGate',
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      'max-video-preview': -1,
      'max-image-preview': 'large',
      'max-snippet': -1,
    },
  },
  verification: {
    google: process.env.GOOGLE_SITE_VERIFICATION || 'tKhN1veJe2nKYfDKpyWVldjh3KLbfXbEFRMigQMIZ28',
    // Note: The verification code should match the one in Google Search Console
    // If using HTML tag method, this should be the code from the meta tag content attribute
  },
}

// Root layout - Next.js requires <html> and <body> in root layout
// With localePrefix: 'always', all routes go through [locale]/layout.jsx
// The nested layout will override the lang/dir attributes via its own <html> tag
// But Next.js still requires root layout to have <html>/<body>
import Providers from './Providers';
import IntlProvider from './IntlProvider';

const SITE_URL = process.env.NEXT_PUBLIC_SITE_URL || 'https://www.aqaargate.com';

// Note: Organization/LocalBusiness with @id #organization is defined in StructuredData.jsx
// to avoid duplicate/conflicting definitions. Organization type does NOT support aggregateRating
// in Google's rich results; LocalBusiness does. Root layout only defines WebSite.
const jsonLd = {
  '@context': 'https://schema.org',
  '@graph': [
    {
      '@type': 'WebSite',
      '@id': `${SITE_URL}/#website`,
      url: SITE_URL,
      name: 'AqaarGate',
      alternateName: ['AqaarGate Real Estate', 'aqaargate', 'aqaargate.com', 'best real estate sites in Syria', 'موقع عقاري', 'موقع عقارات', 'عقارات في سورية', 'عقارات في سوريا', 'سوق العقارات الإلكتروني في سورية', 'عقار جيت'],
      description: 'AqaarGate is one of the best real estate sites in Syria. The #1 real estate platform in Syria & Lattakia. Buy, rent & sell properties, holiday homes, villas, apartments.',
      publisher: { '@id': `${SITE_URL}/#organization` },
      inLanguage: ['en', 'ar'],
    },
  ],
};

export default function RootLayout({ children }) {
  // Root layout must have <html> and <body> for Next.js
  // The [locale]/layout.jsx will provide locale-specific <html> with lang/dir
  // Next.js will use the nested layout's <html> instead of this one
  return (
    <html lang="en" dir="ltr" suppressHydrationWarning>
      <body>
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }}
        />
        <Providers>
          <IntlProvider>
            {children}
          </IntlProvider>
        </Providers>
      </body>
    </html>
  );
}
