export const metadata = {
  title: 'Syria & Lattakia Real Estate - Premium Properties for Sale & Rent | Perfect for Expats from EU & Gulf | AqaarGate',
  description: 'Discover luxury homes, apartments, and holiday homes (بيوت عطلات) for sale and rent (بيع وتأجير) in Syria and Lattakia. Expert real estate guidance for expats from Germany, Netherlands, EU countries, and Arab Gulf (UAE, Saudi Arabia, Qatar, Kuwait, Bahrain, Oman). Your trusted property partner in Syria.',
  keywords: [
    'syria real estate',
    'lattakia real estate',
    'syria properties for sale',
    'syria properties for rent',
    'lattakia properties for sale',
    'lattakia properties for rent',
    'syria holiday homes',
    'lattakia holiday homes',
    'syria vacation rentals',
    'lattakia vacation rentals',
    'syria luxury homes',
    'lattakia luxury homes',
    'syria apartments',
    'lattakia apartments',
    'syria houses',
    'lattakia houses',
    'syria commercial properties',
    'lattakia commercial properties',
    'syria property listings',
    'lattakia property listings',
    'syria real estate agent',
    'lattakia real estate agent',
    'syria property search',
    'lattakia property search',
    'syria beach properties',
    'lattakia beach properties',
    'syria coastal properties',
    'lattakia coastal properties',
    'syria villas',
    'lattakia villas',
    'syria property investment',
    'lattakia property investment',
    'syria land for sale',
    'lattakia land for sale',
    // Arabic keywords for holiday homes
    'بيوت عطلات',
    'بيوت عطلات سوريا',
    'بيوت عطلات اللاذقية',
    'بيوت عطلات للبيع',
    'بيوت عطلات للإيجار',
    'بيع بيوت عطلات',
    'تأجير بيوت عطلات',
    'بيع وتأجير بيوت',
    'بيع وتأجير بيوت عطلات',
    'بيع وتأجير بيوت في سوريا',
    'بيوت عطلات على الشاطئ',
    'بيوت عطلات ساحلية',
    'إيجار منازل عطلات',
    'منازل عطلات للايجار',
    'استئجار بيت عطلة',
    'بيوت عطلات للعائلات'
  ],
  openGraph: {
    title: 'Syria & Lattakia Real Estate - Premium Properties for Sale & Rent | AqaarGate',
    description: 'Discover luxury homes, apartments, and holiday homes (بيوت عطلات) for sale and rent (بيع وتأجير) in Syria and Lattakia. Expert real estate guidance with AqaarGate Real Estate.',
    url: process.env.NEXT_PUBLIC_SITE_URL || 'https://www.aqaargate.com',
    images: [
      {
        url: '/images/section/hero-bg.jpg',
        width: 1200,
        height: 630,
        alt: 'Premium Real Estate Properties',
      },
    ],
  },
  twitter: {
    card: 'summary_large_image',
    title: 'Premium Real Estate Properties - Find Your Dream Home',
    description: 'Discover luxury homes, apartments, and commercial properties for sale and rent.',
    images: ['/images/section/hero-bg.jpg'],
  },
  alternates: {
    canonical: process.env.NEXT_PUBLIC_SITE_URL || 'https://www.aqaargate.com',
  },
}

import HomePageClient from './HomePageClient'

export default function Home() {
  return <HomePageClient />
}
