export default function robots() {
  const baseUrl = process.env.NEXT_PUBLIC_SITE_URL || 'https://www.aqaargate.com';
  
  return {
    rules: [
      {
        userAgent: '*',
        allow: [
          '/',
          '/property-list',
          '/property-detail',
          '/agents',
          '/agents-details',
          '/blog-grid',
          '/contact',
          '/faq',
          '/about-us',
          '/vision',
          '/career',
          '/terms-and-conditions',
          '/privacy-policy',
          '/property-rental-service',
          '/future-buyer-interest',
        ],
        disallow: [
          '/dashboard/',
          '/add-property/',
          '/my-profile/',
          '/my-property/',
          '/messages/',
          '/my-favorites/',
          '/my-package/',
          '/my-save-search/',
          '/review/',
          '/admin/',
          '/api/',
          '/dev-tools/',
          '/private/',
          '/property-filter-popup',
          '/property-filter-popup-left',
          '/property-half-top-map',
          '/agency-grid',
          '/agency-list',
          '/ar-bh',
          '/ar-ae',
          '/ar-kw',
          '/favicon.ico',
        ],
        crawlDelay: 1,
      },
      {
        userAgent: 'Googlebot',
        allow: '/',
        disallow: [
          '/dashboard/',
          '/add-property/',
          '/my-profile/',
          '/my-property/',
          '/messages/',
          '/my-favorites/',
          '/my-package/',
          '/my-save-search/',
          '/review/',
          '/dev-tools/',
          '/api/',
          '/admin/',
          '/private/',
          '/property-filter-popup',
          '/property-filter-popup-left',
          '/property-half-top-map',
          '/agency-grid',
          '/agency-list',
          '/ar-bh',
          '/ar-ae',
          '/ar-kw',
          '/favicon.ico',
        ],
        crawlDelay: 0,
      },
    ],
    sitemap: `${baseUrl}/sitemap.xml`,
    host: baseUrl,
  };
}

